### ISSUE TITLE
Visualización_datos_Buscando_dentro_del_tec

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-tec-design#1]
[REPORTE_2_VISUALIZACIÓN.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-tec-design/files/15458868/REPORTE_2_VISUALIZACION.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
